{% set _version_match = load_file_regex(
  load_file="gpytorch/version.py",
  regex_pattern="__version__ = version = '(.+)'"
) %}
{% set version = _version_match[1] %}

package:
  name: gpytorch
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  script: "$PYTHON ./setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - python>=3.10

  run:
    - python>=3.10
    - jaxtyping
    - linear_operator>=0.6
    - mpmath>=0.19,<=1.3
    - pytorch>=2.0
    - scikit-learn

test:
  imports:
    - gpytorch
    - gpytorch.distributions
    - gpytorch.functions
    - gpytorch.kernels
    - gpytorch.lazy
    - gpytorch.likelihoods
    - gpytorch.means
    - gpytorch.mlls
    - gpytorch.models
    - gpytorch.priors
    - gpytorch.utils
    - gpytorch.variational

about:
  home: https://gpytorch.ai
  license: MIT
  license_file: LICENSE
  summary: An implementation of Gaussian Processes in Pytorch
  doc_url: https://gpytorch.readthedocs.io/en/latest/
  dev_url: https://github.com/cornellius-gp/gpytorch
