# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GPyTorch Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pytorch-version: ["master", "stable"]
        pyro: ["with-pyro", "no-pyro"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        if [[ ${{ matrix.pytorch-version }} = "master" ]]; then
          pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html;
        else
          pip install torch==1.9+cpu -f https://download.pytorch.org/whl/torch_stable.html;
        fi
        if [[ ${{ matrix.pyro }} == "with-pyro" ]]; then
          pip install "pyro-ppl<=1.8";
        fi
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        python -m unittest discover
